<a href="https://colab.research.google.com/github/bekka9/Testing-hypotheses-about-the-parameters-of-the-normal-distribution/blob/main/mat_stat_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3
 Проверка гипотез о параметрах нормального распределения

In [ ]:
import pandas as pd
import statistics
import numpy as np
import pandas
import scipy.stats as stats
import statistics as stat
import statsmodels

df = pd.DataFrame(pd.read_excel("/content/mat_stat_3(14)1.xlsx"))
df

,X1,X2,Y1,Y2,Z1,Z2,Z3,Z4
0,48.958495,55.281289,54.265809,50.567141,46.320679,47.912575,45.315411,43.361453
1,55.526447,57.795086,53.907692,50.527342,47.211911,53.521815,47.098539,48.228168
2,55.839241,56.574108,51.836773,48.170895,47.500839,46.317066,47.256691,52.863462
3,47.868834,57.210481,59.520662,52.075320,48.091319,50.020447,47.659143,47.225195
4,60.027136,53.177732,53.359219,54.658862,48.878605,44.064703,47.790628,45.393337
5,54.102315,55.877071,48.204328,50.799399,48.926317,54.026780,47.997561,59.482173
6,56.467911,56.006692,50.864955,50.348498,49.407513,54.559853,48.067069,55.781967
7,65.875847,52.971572,57.935856,50.867311,49.526570,56.781967,48.141870,53.977193
8,56.690773,46.824079,52.345758,56.786357,49.540317,51.756777,48.327112,49.832421
9,48.418146,56.760363,53.089284,53.687194,49.736886,47.181705,48.340966,47.601299
10,55.330406,61.718692,53.307269,57.478664,50.105518,53.667593,48.381418,51.041790
11,63.699117,49.222380,50.500661,47.330086,50.110065,50.582633,48.484163,49.178949
12,49.701693,52.856585,58.710636,52.343102,50.652413,56.173661,48.624057,48.460544
13,71.057020,59.806607,52.863362,44.481003,50.882797,52.215340,48.660655,50.701398
14,50.524345,58.859523,53.157936,56.843682,50.975504,50.923957,49.022846,55.469428
15,59.205522,60.389466,58.250177,57.665683,51.146876,54.225286,49.095819,47.153518
16,53.851745,51.857459,58.026857,51.069691,51.207155,52.782978,49.097513,50.928867
17,52.783966,52.596906,56.496580,59.306157,51.259028,52.293124,49.205334,54.217636
18,49.294235,60.162383,50.537073,64.146534,51.437523,52.912695,49.250499,52.079400
19,49.977434,61.745177,57.038693,52.961472,51.454058,45.313785,49.289421,57.796807
20,51.253041,54.727606,49.319487,56.619842,51.749271,53.317147,49.410729,45.141343
21,52.819300,61.272967,54.213433,61.422779,51.851379,48.616669,49.413446,45.402231
22,54.341637,58.338832,56.161018,58.409150,51.924785,54.621199,49.460565,48.296767
23,60.910360,60.862275,54.622057,52.798423,52.012928,45.733125,49.470713,54.555377
24,59.449025,54.734355,60.983893,54.639203,52.285618,50.429383,49.473089,50.179216
25,63.633988,54.182387,53.380501,49.522768,52.391015,53.154729,49.553154,42.540434
26,55.710108,51.205288,51.542772,50.735125,52.524694,57.573919,49.577749,58.035240
27,47.040330,56.636795,53.807008,56.809717,52.762152,53.697861,49.736006,51.854232
28,58.581033,60.886577,58.391629,48.658075,52.781438,49.688163,49.973454,49.555857
29,41.680959,55.201580,53.172325,51.840352,53.296949,44.844649,49.978197,49.804850
30,47.998328,52.141285,48.764377,56.344170,53.311330,58.188173,49.997781,54.141048
31,59.671438,47.301055,57.470144,58.268251,53.425410,56.721740,50.019354,48.697522
32,56.860055,49.960435,53.561877,53.029125,53.612643,54.244813,50.049040,50.325781
33,60.264501,51.949127,61.831960,55.362334,53.878011,47.851620,50.111977,50.119817
34,47.774960,52.395525,54.354181,56.691178,53.967883,51.541268,50.339674,52.851220
35,47.929870,51.052793,58.073801,61.672744,54.058796,46.449307,50.680996,47.209989
36,51.404144,53.717512,57.356278,53.271605,54.071833,55.634694,50.777311,46.893166
37,42.912379,56.101416,56.334699,51.169136,54.982706,41.750221,50.792184,46.687975
38,54.523293,59.111880,52.627126,49.328882,55.168807,51.902478,50.878160,50.069922
39,56.210492,50.578437,55.501130,55.444761,56.741087,44.222882,51.012822,48.228841
40,61.011860,52.487139,53.194651,57.403094,NaN,47.679344,51.099008,51.507869
41,63.425941,53.858798,53.024175,54.613083,NaN,49.378830,51.234330,55.296879
42,57.043471,55.257060,53.633807,59.146805,NaN,41.772194,51.301291,47.738360
43,55.520922,61.508672,55.794882,49.593800,NaN,50.665924,51.313988,52.877714
44,55.804494,56.084900,52.619275,49.749824,NaN,44.902984,52.000670,52.186994
45,51.638726,48.280035,57.492436,56.148851,NaN,54.983214,52.134871,NaN
46,52.480784,53.940475,49.616919,59.031226,NaN,56.480351,52.408979,NaN
47,45.516062,49.831287,52.302716,49.946875,NaN,52.635131,53.153873,NaN
48,63.152997,63.290408,51.778561,48.519923,NaN,50.881716,53.487767,NaN
49,64.260120,50.713997,55.518357,57.973675,NaN,50.270931,55.121983,NaN

In [ ]:
var_x1 = 36
#var_x2 = undefined
a_0 = 40
sd_0 = 4
var_y1 = 9
#var_y2 = und
alpha = 0.05

## Пункт №1

Гипотеза о значении математического ожидания при известной дисперсии (one-sampled z-test).

In [ ]:
n = len(df['X1'])
z_score = (stat.fmean(df["X1"])-a_0)/(np.sqrt(var_x1)/np.sqrt(n))
z_critical = stats.norm.ppf(1-alpha)

if z_score >  z_critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")

reject null hypothesis

In [ ]:
#import statsmodels.stats.weightstats.ztest as ztest
#statsmodels.stats.weightstats.ztest(x1, x2=None, value=0, alternative='two-sided', usevar='pooled', ddof=1.0)

## Пункт №2

Гипотеза о значении математического ожидания при неизвестной дисперсии (one-sample t-test)

In [ ]:
var = stat.variance(df["X2"], xbar=None)
n = len(df['X2'])
t_score = (stat.fmean(df["X2"])-a_0)/(np.sqrt(var)/np.sqrt(n))
t_critical = stats.t.ppf(1 - alpha, n - 1)

if t_score >  t_critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")

reject null hypothesis

## Пункт №3

Гипотеза о значении дисперсии при неизвестном математическом ожидании (chi-squared test)

In [ ]:
var = stat.variance(df["X2"], xbar=None)
n = len(df['X2'])
statistic = (n - 1)*(stat.stdev(df['X2'])**2)/(sd_0**2)
critical = stats.chi2.ppf(1 - alpha, n - 1)

if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")

null hypothesis

## Пункт №4

Гипотеза о равенстве математических ожиданий при известных дисперсиях (two-sample z-test)

In [ ]:
n1 = len(df['X1'])
n2 = len(df['Y1'])
statistic = (stat.fmean(df["X1"])-stat.fmean(df["Y1"]))/np.sqrt(var_x1/n1 + var_y1/n2)
critical = stats.norm.ppf(1 - alpha)

if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")

null hypothesis

## Пункт №5

Гипотеза о равенстве математических ожиданий при неизвестных дисперсиях (two-sample unpooled t-test).

In [ ]:
n1 = len(df['X2'])
n2 = len(df['Y2'])
var = ((n1 - 1)*stat.stdev(df['X2'])**2 + (n2 - 1)* stat.stdev(df['Y2'])**2)/(n1 + n2 - 2)
sd = np.sqrt(var)

statistic = (stat.fmean(df["X2"])-stat.fmean(df["Y2"]))/(sd*np.sqrt(1/n1 + 1/n2))
critical = stats.t.ppf(1 - alpha, n1 + n2 - 2)

if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")

null hypothesis

## Пункт №6


Гипотеза о равенстве дисперсий при неизвестных математических ожиданиях (two-sample F-test).

In [ ]:
n1 = len(df['X2'])
n2 = len(df['Y2'])

statistic = ((stat.stdev(df['X2'])**2)/(sd_0**2))/((stat.stdev(df['Y2'])**2)/(sd_0**2))
critical = stats.f.ppf(1 - alpha, n1 - 1, n2 - 1)

if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")

null hypothesis

## Пункт №7

Гипотеза о равенстве математических ожиданий при неизвестных дисперсиях (two-sample unpooled t-test).

In [ ]:
n1 = len(df['Z1']) - df['Z1'].isnull().sum() #40
n2 = len(df['Z2']) - df['Z2'].isnull().sum()
n3 = len(df['Z3']) - df['Z3'].isnull().sum()
n4 = len(df['Z4']) - df['Z4'].isnull().sum() #45


var = ((n1 - 1)*stat.stdev(df['Z1'].dropna())**2 + (n2 - 1)* stat.stdev(df['Z2'])**2)/(n1 + n2 - 2)
sd = np.sqrt(var)
statistic = (stat.fmean(df['Z1'].dropna())-stat.fmean(df["Z2"]))/(sd*np.sqrt(1/n1 + 1/n2))
critical = stats.t.ppf(1 - alpha, n1 + n2 - 2)
if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")


var = ((n2 - 1)*stat.stdev(df['Z2'])**2 + (n3 - 1)* stat.stdev(df['Z3'])**2)/(n3 + n2 - 2)
sd = np.sqrt(var)
statistic = (stat.fmean(df["Z2"])-stat.fmean(df["Z3"]))/(sd*np.sqrt(1/n2 + 1/n3))
critical = stats.t.ppf(1 - alpha, n2 + n3 - 2)
if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")


var = ((n3 - 1)*stat.stdev(df['Z3'])**2 + (n4 - 1)* stat.stdev(df['Z4'].dropna())**2)/(n3 + n4 - 2)
sd = np.sqrt(var)
statistic = (stat.fmean(df["Z3"])-stat.fmean(df["Z4"].dropna()))/(sd*np.sqrt(1/n3 + 1/n4))
critical = stats.t.ppf(1 - alpha, n3 + n4 - 2)
if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")


var = ((n1 - 1)*stat.stdev(df['Z1'].dropna())**2 + (n4 - 1)* stat.stdev(df['Z4'].dropna())**2)/(n1 + n4 - 2)
sd = np.sqrt(var)
statistic = (stat.fmean(df["Z1"].dropna())-stat.fmean(df["Z4"].dropna()))/(sd*np.sqrt(1/n1 + 1/n4))
critical = stats.t.ppf(1 - alpha, n1 + n4 - 2)
if statistic >  critical:
    print("reject null hypothesis")
else:
  print("null hypothesis")

null hypothesis
reject null hypothesis
null hypothesis
null hypothesis

математические ожидания второй и третьей выборок не равны